---
abstract: 'Generate Atom and RSS feeds'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Web-Feed
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
  perl: '5.010'
resources:
  repository: http://github.com/szabgab/Web-Feed.git
version: '0.06'
